compile:
				g++ -o ApproximateEulersNumberMain ApproximateEulersNumberMain.cpp
				g++ -o ApproximateEulersNumberTest ApproximateEulersNumberTest.cpp -lgtest
test:
				./ApproximateEulersNumberTest

checkstyle:
				cpplint *.cpp
clean:
			rm -rf a.out
			rm -rf ApproximateEulersNumberMain
			rm -rf ApproximateEulersNumberTest
